#!/usr/bin/env bash
set -o errexit
#set -x

__DIR__="$(cd "$(dirname "${0}")"; echo $(pwd))"
__BASE__="$(basename "${0}")"
__FILE__="${__DIR__}/${__BASE__}"

# Give permissions to read and write in workdir for users root and apache
setfacl -R -m u:apache:rwx -m u:root:rwx /var/www
setfacl -dR -m u:apache:rwx -m u:root:rwx /var/www

main () {
  /usr/sbin/httpd -DFOREGROUND
}

main